export const actionTypes= {
    LOADING:"LOADING",
    LOADING_SUCCESS:"LOADING_SUCCESS",
    UPDATING:"UPDATING",
    UPDATING_SUCCESS:"UPDATING_SUCCESS",
    SAVE_ALL_AGREEMENTS:"SAVE_ALL_AGREEMENTS"
}